export const SET_ACCOUNT = 'SET_ACCOUNT';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SET_MY_TEAMS = 'SET_MY_TEAMS';
export const SELECT_GROUP = 'SELECT_GROUP';
export const SELECT_MEMBER = 'SELECT_MEMBER';
export const SET_GROUP_MEMBERS = 'SET_GROUP_MEMBERS';
export const SET_MEMBER_NAME_FILTER = 'SET_MEMBER_NAME_FILTER';

